apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello
spec:
  selector:
    matchLabels:
      app: myhello
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: myhello
    spec:
      containers:
      - name: myhello
        image: tomvmac/myhello:2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod